import { CustomHeader, CustomOptions } from "@/utils/interfaces"


type PrepareData = {
    [key in keyof CustomOptions]: string | ""
}
export class NginxSample {
    private static forceHttpsRedirection(host: string = "$host") {
        return `return 301 https://${host}$request_uri;`
    }
    private static ipWhitelist(ip: string[]) {

    }
    static ErrorPages() {
        return `
        error_page 404 /custom_404.html;
        location = /custom_404.html {
                root /usr/share/nginx/html;
                internal;
        }

        error_page 500 502 503 504 /custom_50x.html;
        location = /custom_50x.html {
                root /usr/share/nginx/html;
                internal;
        }`
    }
    static DeafultServer(server_name: string[], destination: string, path: string, options?: CustomOptions) {
        const data: PrepareData = {
            allow_caching: "",
            custom_headers: "",
            has_custom_headers: "",
            websocket_support: "",
            force_https_redirect: "",
            block_exploits: "",
            auto_ssl: "",
            publicly_accessible: ""
        }
        if (options) {
            if (options.force_https_redirect) data["force_https_redirect"] = this.forceHttpsRedirection()
            if (options.has_custom_headers) data["custom_headers"] = this.WithCustomHeaders(options.custom_headers)
            if (options.websocket_support) data["websocket_support"] = this.WebSockets({ destination, path })
            if (options.allow_caching) data["allow_caching"] = this.AllowCaching()
            if (options.block_exploits) data["block_exploits"] = this.BlockExploits()
        }
        return `
            server {
                    listen 80;
                    listen [::]:80;
                    server_name ${server_name.join(' ')};
                    ${data.force_https_redirect}
                    location ${path} {
                        # applying  reverse proxy  
                        # allow 123.456.123.345; 
                        # deny  all;
                        proxy_pass ${destination}; 
                        proxy_http_version 1.1;
                        proxy_set_header Upgrade $http_upgrade;
                        proxy_set_header Connection 'upgrade';
                        proxy_set_header Host $host;                        
                        proxy_cache_bypass $http_upgrade;
                        ${data.custom_headers}
                    }
                    ${data.websocket_support}    
            }
        `
    }
    static HTMLApplication() { }
    static SSL_CONFIG() {
        return {
            path: `
            listen 443 ssl; 
            ssl_certificate /etc/letsencrypt/live/api.saveit.in/fullchain.pem;
            ssl_certificate_key /etc/letsencrypt/live/api.saveit.in/privkey.pem;
            include /etc/letsencrypt/options-ssl-nginx.conf;
            ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; 
            `,
            manage: `                    
                    
            server {
                if ($host = www.api.saveit.in) {
                    return 301 https://$host$request_uri;
                } 

                if ($host = api.saveit.in) {
                    return 301 https://$host$request_uri;
                } 

                server_name api.saveit.in www.api.saveit.in;
                listen 80;
                return 404;

            }
        `
        }
    }
    static DeployApi(server_name: string[], destination: string, path: string) {
        return `
        #  DO NOT EDIT THIS FILE DIRECT , ANY CHANGE WILL CAUSE SERVER CONFIG
            server {
                     listen 80;
                     listen [::]:80;
                     server_name ${server_name.join(' ')};
                     location ${path} {
                        # allow ips; 
                        # deny  all;
                        # applying reverse proxy  
                        proxy_set_header X-Real-IP $remote_addr;
                        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                        proxy_pass ${destination}; 
                        proxy_http_version 1.1;
                        proxy_set_header Upgrade $http_upgrade;
                        proxy_set_header Connection 'upgrade';
                        proxy_set_header Host $host;                        
                        proxy_set_header Created-By 'ServerStackSuite';                        
                        proxy_cache_bypass $http_upgrade;
                         # {custom_headers}                       
                         # {auto_ssl}
                         # {handle_options}                        
    
                }
            }
        `
    }

    static ReactHTMLApplication(server_name: string[], path: string) {
        return `
        server {
                listen 80;
                listen [::]:80;

                root /var/www/your_domain/html;
                index index.html index.htm index.nginx-debian.html;

                server_name ${server_name.join(' ')};

                location / {
                        try_files $uri $uri/ =404;
                }
        }
        `
    }
    static ReactServeApplication(server_name: string[], path: string) {
        return `
        server {
                listen 80;
                listen [::]:80;

                root /var/www/your_domain/html;
                index index.html index.htm index.nginx-debian.html;

                server_name ${server_name.join(' ')};

                location / {
                         
                }
        }
        `
    }
    static NextOutApplication() {
        return `
     server {
                listen 80 default_server;
                listen [::]:80;
                
                server_name www.DOMAINNAME.com DOMAINNAME.com;

                index index.html index.htm;
                root /home/ubuntu/PROJECT_FOLDER; #Make sure your using the full path

                # Serve any static assets with NGINX
                location /_next/static {
                    alias /home/ubuntu/PROJECT_FOLDER/.next/static;
                    add_header Cache-Control "public, max-age=3600, immutable";
                }

                location / {
                    try_files $uri.html $uri/index.html # only serve html files from this dir
                    @public
                    @nextjs;
                    add_header Cache-Control "public, max-age=3600";
                }

                location @public {
                    add_header Cache-Control "public, max-age=3600";
                }

                location @nextjs {
                    # reverse proxy for next server
                    proxy_pass http://localhost:8080; #Don't forget to update your port number
                    proxy_http_version 1.1;
                    proxy_set_header Upgrade $http_upgrade;
                    proxy_set_header Connection 'upgrade';
                    proxy_set_header Host $host;
                    proxy_cache_bypass $http_upgrade;
                }

               
        }
        `
    }
    static NextSSRApplication() { }
    static WithSocketSupport() { }
    static WithCustomHeaders(headers: Record<string, string> | CustomHeader[]) {
        let headersString = ''
        for (const key in headers) {
            headersString += `proxy_set_header ${key} ${headers[key as keyof typeof headers]} \n`
        }

        return headersString
    }
    static WithCacheSupport() { }

    static Redirection() {
        return ``
    }
    static BlockExploits() {
        return `
         ## Block SQL injections
    set $block_sql_injections 0;
    if ($query_string ~ "union.*select.*\(") {
        set $block_sql_injections 1;
    }
    if ($query_string ~ "union.*all.*select.*") {
        set $block_sql_injections 1;
    }
    if ($query_string ~ "concat.*\(") {
        set $block_sql_injections 1;
    }
    if ($block_sql_injections = 1) {
        return 403;
    }

    ## Block file injections
    set $block_file_injections 0;
    if ($query_string ~ "[a-zA-Z0-9_]=http://") {
        set $block_file_injections 1;
    }
    if ($query_string ~ "[a-zA-Z0-9_]=(\.\.//?)+") {
        set $block_file_injections 1;
    }
    if ($query_string ~ "[a-zA-Z0-9_]=/([a-z0-9_.]//?)+") {
        set $block_file_injections 1;
    }
    if ($block_file_injections = 1) {
        return 403;
    }

    ## Block common exploits
    set $block_common_exploits 0;
    if ($query_string ~ "(<|%3C).*script.*(>|%3E)") {
        set $block_common_exploits 1;
    }
    if ($query_string ~ "GLOBALS(=|\[|\%[0-9A-Z]{0,2})") {
        set $block_common_exploits 1;
    }
    if ($query_string ~ "_REQUEST(=|\[|\%[0-9A-Z]{0,2})") {
        set $block_common_exploits 1;
    }
    if ($query_string ~ "proc/self/environ") {
        set $block_common_exploits 1;
    }
    if ($query_string ~ "mosConfig_[a-zA-Z_]{1,21}(=|\%3D)") {
        set $block_common_exploits 1;
    }
    if ($query_string ~ "base64_(en|de)code\(.*\)") {
        set $block_common_exploits 1;
    }
    if ($block_common_exploits = 1) {
        return 403;
    }

    ## Block spam
    set $block_spam 0;
    if ($query_string ~ "\b(ultram|unicauca|valium|viagra|vicodin|xanax|ypxaieo)\b") {
        set $block_spam 1;
    }
    if ($query_string ~ "\b(erections|hoodia|huronriveracres|impotence|levitra|libido)\b") {
        set $block_spam 1;
    }
    if ($query_string ~ "\b(ambien|blue\spill|cialis|cocaine|ejaculation|erectile)\b") {
        set $block_spam 1;
    }
    if ($query_string ~ "\b(lipitor|phentermin|pro[sz]ac|sandyauer|tramadol|troyhamby)\b") {
        set $block_spam 1;
    }
    if ($block_spam = 1) {
        return 403;
    }

    ## Block user agents
    set $block_user_agents 0;

    # Don't disable wget if you need it to run cron jobs!
    #if ($http_user_agent ~ "Wget") {
    #    set $block_user_agents 1;
    #}

    # Disable Akeeba Remote Control 2.5 and earlier
    if ($http_user_agent ~ "Indy Library") {
        set $block_user_agents 1;
    }

    # Common bandwidth hoggers and hacking tools.
    if ($http_user_agent ~ "libwww-perl") {
        set $block_user_agents 1;
    }
    if ($http_user_agent ~ "GetRight") {
        set $block_user_agents 1;
    }
    if ($http_user_agent ~ "GetWeb!") {
        set $block_user_agents 1;
    }
    if ($http_user_agent ~ "Go!Zilla") {
        set $block_user_agents 1;
    }
    if ($http_user_agent ~ "Download Demon") {
        set $block_user_agents 1;
    }
    if ($http_user_agent ~ "Go-Ahead-Got-It") {
        set $block_user_agents 1;
    }
    if ($http_user_agent ~ "TurnitinBot") {
        set $block_user_agents 1;
    }
    if ($http_user_agent ~ "GrabNet") {
        set $block_user_agents 1;
    }

    if ($block_user_agents = 1) {
        return 403;
    }
        `
    }
    static AllowCaching() {
        return ``
    }
    static WebSockets({
        path = "/socket.io/",
        destination
    }: {
        path: string,
        destination: string

    }) {
        return `
         
         location ${path} {
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $host;
            proxy_pass ${destination};
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
         }
        
        `
    }
}