export enum SOCKET_EVENTS {
    REALTIME_SERVER_USAGE = "REALTIME_SERVER_USAGE",
    REALTIME_SERVER_USAGE_LOG = "REALTIME_SERVER_USAGE_LOG",
    REALTIME_SERVER_STATUS = "REALTIME_SERVER_STATUS",
    REALTIME_SERVER_OPERATION_LOGS = "REALTIME_SERVER_OPERATION_LOGS",
    REALTIME_SERVER_CONFIG = "REALTIME_SERVER_CONFIG",

    UPDATE_PACKAGES = "UPDATE_PACKAGES",
    CHECK_PACKAGES_REQUIREMENTS = "CHECK_PACKAGES_REQUIREMENTS",

    STATUS_SERVER = "STATUS_SERVER",
    STOP_SERVER = "STOP_SERVER",
    START_SERVER = "START_SERVER",
    RESTART_SERVER = "RESTART_SERVER",
    RELOAD_SERVER_CONFIG_FILES = "RELOAD_SERVER_CONFIG_FILES",
    TEST_CONF_FILE = "TEST_CONF_FILE",

    CONNECT_TERMINAL = "@@CONNECT_TERMINAL",
    SSH_EMIT_RESIZE = "@@SSH_EMIT_RESIZE",

    SEND_COMMAND = "@@SEND_COMMAND",
    RECIEVE_COMMAND = "@@RECIEVE_COMMAND",
    RECIEVE_LOGS_ONLY= "@@RECIEVE_LOGS_ONLY",

    NOTIFICATIONS = "@@NOTIFICATIONS",

    FILE_CHANGE = "@@FILE_CHANGE",

    MANAGE_FIREWALL = "@@MANAGE_FIREWALL",
    MANAGE_PORTS = "@@MANAGE_PORTS",    

}

