export enum SOCKET_EVENTS {
    REALTIME_SERVER_USAGE = "REALTIME_SERVER_USAGE",
    SYSTEM_INFORMATION = "SYSTEM_INFORMATION",
    REALTIME_SERVER_OPERATION_LOGS = "REALTIME_SERVER_OPERATION_LOGS",

    UPDATE_PACKAGES = "UPDATE_PACKAGES",
    CHECK_PACKAGES_REQUIREMENTS = "CHECK_PACKAGES_REQUIREMENTS",

    STATUS_SERVER = "STATUS_SERVER",
    STOP_SERVER = "STOP_SERVER",
    START_SERVER = "START_SERVER",
    RESTART_SERVER = "RESTART_SERVER",
    RELOAD_SERVER_CONFIG_FILES = "RELOAD_SERVER_CONFIG_FILES",
    TEST_CONF_FILE = "TEST_CONF_FILE",

    CONNECT_TERMINAL = "@@CONNECT_TERMINAL",
    SSH_EMIT_RESIZE = "@@SSH_EMIT_RESIZE",

    SEND_COMMAND = "@@SEND_COMMAND",
    RECIEVE_COMMAND = "@@RECIEVE_COMMAND",
    RECIEVE_LOGS_ONLY = "@@RECIEVE_LOGS_ONLY",

    NOTIFICATIONS = "@@NOTIFICATIONS",

    FILE_CHANGE = "@@FILE_CHANGE",

    MANAGE_FIREWALL = "@@MANAGE_FIREWALL",
    MANAGE_PORTS = "@@MANAGE_PORTS",

    DEPLOYMENT_LOGS = "@@DEPLOYMENT_LOGS",
    DEPLOYMENT_STATUS = "@@DEPLOYMENT_STATUS",

    CONTAINER_SHELL_START = "@@CONTAINER_SHELL_START",
    CONTAINER_SHELL_RESIZE = "@@CONTAINER_SHELL_RESIZE",
    CONTAINER_SHELL_MESSAGE = "@@CONTAINER_SHELL_MESSAGE",
    CONTAINER_SHELL_INPUT = "@@CONTAINER_SHELL_INPUT",

    CONTAINER_LOGS_START = "@@CONTAINER_LOGS_START",
    CONTAINER_LOGS = "@@CONTAINER_LOGS",
    CONTAINER_LOGS_STOP = "@@CONTAINER_LOGS_STOP",
    CONTAINER_STATS = "@@CONTAINER_STATS",
    CONTAINER_STATS_STOP = "@@CONTAINER_STATS_STOP",
    
    SYSTEMD_SERVICES = "@@SYSTEMD_SERVICES",
    SYSTEMD_SERVICE_STATUS = "@@SYSTEMD_SERVICE_STATUS",
}

