FROM {{NODE_VERSION}}-alpine AS builder

WORKDIR /app

COPY package*.json ./

RUN {{{INSTALL}}}

COPY . .

RUN {{BUILD}}

FROM {{NODE_VERSION}}-alpine AS production

WORKDIR /app

COPY --from=builder /app/build ./build
COPY --from=builder /app/package*.json ./

RUN {{{INSTALL}}}

EXPOSE {{PORT}}

CMD {{{START}}}